import { NextResponse, type NextRequest } from 'next/server'
import { z } from 'zod'

import { serveChat } from '@/lib/chat/serve'
import { appUrl } from '@/lib/env'
import { effectiveOrigin } from '@/lib/security/embed-origin'
import { checkOrigin } from '@/lib/security/origin'
import { createAdminClient } from '@/lib/supabase/admin'

/**
 * Chat for anonymous visitors on a customer's website.
 *
 * The bot id is visible in the page source of every site running the widget and
 * can never be a secret, so this endpoint authorizes explicitly instead:
 *
 *   1. the Origin header against the bot's allowed domains
 *   2. a per-IP, per-bot rate limit
 *   3. the owner's remaining monthly allowance, inside serveChat
 *
 * Kept as its own file rather than a branch inside the authenticated route.
 * Two authorization models in one handler is where a mistake quietly grants a
 * visitor the powers of an account owner.
 */

const bodySchema = z.object({
  botId: z.uuid(),
  question: z.string().trim().min(1).max(2000),
  conversationId: z.uuid().nullable().optional(),
  /** Anonymous, generated by the widget and kept in the visitor's browser. */
  visitorId: z.string().max(64).nullable().optional(),
  /** Host page the widget is embedded in; see effectiveOrigin below. */
  hostSite: z.string().max(255).nullable().optional(),
})

/** Requests per IP per bot. Generous for a person, restrictive for a script. */
const RATE_LIMIT_MAX = 20
const RATE_LIMIT_WINDOW_SECONDS = 60

/** CORS: the widget runs inside an iframe on the customer's domain. */
function corsHeaders(origin: string | null): Record<string, string> {
  return {
    'Access-Control-Allow-Origin': origin ?? '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    Vary: 'Origin',
  }
}

export async function OPTIONS(request: NextRequest) {
  return new Response(null, { status: 204, headers: corsHeaders(request.headers.get('origin')) })
}

export async function POST(request: NextRequest) {
  const origin = request.headers.get('origin')
  const headers = corsHeaders(origin)

  const parsed = bodySchema.safeParse(await request.json().catch(() => null))

  if (!parsed.success) {
    return NextResponse.json({ error: 'Некорректный запрос.' }, { status: 400, headers })
  }

  const admin = createAdminClient()

  const { data: bot } = await admin
    .from('bots')
    .select('id, owner_id, name, allowed_domains, is_active')
    .eq('id', parsed.data.botId)
    .maybeSingle()

  if (!bot || !bot.is_active) {
    return NextResponse.json({ error: 'Ассистент сейчас недоступен.' }, { status: 404, headers })
  }

  const verdict = checkOrigin(
    effectiveOrigin(origin, parsed.data.hostSite, appUrl()),
    bot.allowed_domains,
  )

  if (!verdict.allowed) {
    // Deliberately vague to the caller: naming the allowed domains would tell
    // whoever copied the snippet exactly what to spoof.
    return NextResponse.json(
      { error: 'Ассистент недоступен на этом сайте.' },
      { status: 403, headers },
    )
  }

  const ip =
    request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
    request.headers.get('x-real-ip') ??
    'unknown'

  const { data: limit } = await admin.rpc('check_rate_limit', {
    p_key: `chat:${bot.id}:${ip}`,
    p_max: RATE_LIMIT_MAX,
    p_window_seconds: RATE_LIMIT_WINDOW_SECONDS,
  })

  if (limit?.[0] && !limit[0].allowed) {
    return NextResponse.json(
      { error: 'Слишком много сообщений. Подождите немного.' },
      { status: 429, headers },
    )
  }

  const response = serveChat({
    bot: { id: bot.id, owner_id: bot.owner_id, name: bot.name },
    conversationId: parsed.data.conversationId ?? null,
    source: 'widget',
    visitorId: parsed.data.visitorId ?? null,
    question: parsed.data.question,
  })

  for (const [name, value] of Object.entries(headers)) {
    response.headers.set(name, value)
  }

  return response
}
